import './globals.css';
import Navbar from './components/Navbar';
import Footer from './components/Footer';
import PageHeader from './components/PageHeader';

export const metadata = {
  title: 'ديم السحاب',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ar" dir="rtl">
      <body>
        <Navbar />
        <main>
          <PageHeader />
          {children}
        </main>
        <Footer />
      </body>
    </html>
  )
}
